apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestash
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filestash
  template:
    metadata:
      labels:
        app: filestash
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 1000
      containers:
        - name: filestash
          image: machines/filestash@sha256:9bd9e188b83897b8041a52d3ba6def9209447143e3300382c82d41ecf057ab90
          ports:
            - containerPort: 8334
          volumeMounts:
            - name: data
              mountPath: /app/data/storage # Filestash still sees this internal path
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: irminsul-records-pvc # Changed to point to the shared volume
