apiVersion: apps/v1
kind: Deployment
metadata:
  name: suwayomi
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: suwayomi
  template:
    metadata:
      labels:
        app: suwayomi
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: suwayomi
          image: ghcr.io/suwayomi/suwayomi-server:v2.2.2100
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: TZ
              value: America/Detroit
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: FLARESOLVERR_ENABLED
              value: "true"
            - name: FLARESOLVERR_URL
              value: "http://flaresolverr:8191"
            - name: FLARESOLVERR_TIMEOUT
              value: "60000"
          ports:
            - containerPort: 4567
          volumeMounts:
            - name: config
              mountPath: /home/suwayomi/.local/share/Tachidesk
            - name: manga
              mountPath: /home/suwayomi/.local/share/Tachidesk/downloads/mangas
              subPath: manga
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: suwayomi-config-pvc
        - name: manga
          persistentVolumeClaim:
            claimName: irminsul-records-celestia-pvc
