apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: suwayomi-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    metallb.io/loadBalancerIPs: 192.168.1.52
spec:
  rules:
    - host: suwayomi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: suwayomi
                port:
                  number: 4567
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: suwayomi
                port:
                  number: 4567
