apiVersion: v1
kind: Secret
metadata:
    name: minio-root-creds
    namespace: minio
stringData:
    rootUser: ENC[AES256_GCM,data:uU60kMEttrWYb12r,iv:wpCdUwTEh1bBHt/RCAqxn5d9f9daOCnIHCBbV/QgSKg=,tag:+M89ZT/d0KECHBsEfKMG6w==,type:str]
    rootPassword: ENC[AES256_GCM,data:4C4SdH8Go8ElU5c0QoCdK02cK9Oxg2nbIWrygboZxSI=,iv:jAStlmGpFOYAXlAMmuv3wpCG57Ss0+Xx7F99WQfwkNE=,tag:1ww4priiVExTM3VWRTwrWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpM0JURmpERzNydUpNbEJP
            Zm5yREN6LzVJRkhMZ3QzaWF4QVcyd1dLN1VnCnhqUHc1MlpQY2d6dnh6U0F6enpx
            T05teWVNMVVtSTcwZS9VeC85TE5MVlEKLS0tIC9BOGtJNlZ0MzBXanFtZjdjMFpv
            ODRWR1FpVzJyRndXb0FVVzd3bVFnSkEKnmC8My6d5fE7gOaOxEgxSbZo8pDCgQgB
            SjJvjEhJ+ek9b2/Ddm71on7zslvTImFoWqfWoVgyjE2Qq/PZnZ5DEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1skrf3yyvljnepgfjpz8tf205tygaycxh68h7t2c6amwtaf0qsgjqzd743s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T00:41:52Z"
    mac: ENC[AES256_GCM,data:+f3A1/VVjGvHZwFDky2MIrTsgdALAsZYGzPgIknArSN9pKQntIawuj4PpbIJ6PiNaEKM4lHX4pS73D1dC7W42E97AsMj5mEXGgQP2Cktqg7bHEbjMWKnUoxHq1xpWDhYoWaV+mlKS9xrVe5OCdgpZbBnMTZFqGe5Q9A+j49glQw=,iv:b2nWzuC/nVudmQgbmb29Jyv3sQtyWQM+fHhYQK/vg0s=,tag:t+zRw8OhBYHMsh4UdEf3vg==,type:str]
    version: 3.13.3
