apiVersion: v1
kind: Secret
metadata:
    name: ntfy-url
    namespace: monitoring
stringData:
    url: ENC[AES256_GCM,data:JLtMbgXbBXiXRh4oD4IvhwGPntAqhr1CNHw53lQ7zUFgGN9cI3Q+JcKBeLClq32jAJpofsTxhrxvtAlVho11vA==,iv:vHYKLKbxop8Fy4if1p2XQtk1mk90h3g7Py6ydm4S0Q0=,tag:tjIzktvBDQJG5YM66oeyFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwY2VBd3RiWERHc0hHQmhw
            TDRjakgwbGxQdXVvRnQveDBVVGRUV1g5Qlg0CktqSkNUR0pqNXNUTGhqZi9NNTNX
            NGREbUlFdXl3ZExJeVBJNWpGQTB2VWsKLS0tIHFmN2ttazVyQVV5Q3BGK2ZMNytR
            QVVpTGJXVG9PQzRSMUN5K3UzT0tyd00Kxgl+p8ER4YakGgL9PHaSYSsUpvfWm4d8
            nOQk8iNIod3zs4hGNZcuU7Y64qca42xny7t1q0Z2fbMZGkTdiR2H/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1skrf3yyvljnepgfjpz8tf205tygaycxh68h7t2c6amwtaf0qsgjqzd743s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T00:50:08Z"
    mac: ENC[AES256_GCM,data:fzeiefB7WvwYJwbhJZZTSA5BimGV1jglfLjAf8LTHFgwvj+yZURQlZLjeOxs3qpj+CYdx+ZztQWFDtT8mToyebaoHM9W418jht1th10hygNh1slfkFmsU0/HYeGMf1VmNkNADKEQVt06O2lQ/NTVZDZ9FL+DrGpzir9yNGT/4Fs=,iv:fNyiF4AWqUmtMqojGcm+/uiJEClHxbU/ulBlGX3oB7k=,tag:px0JQ2B7eEP28aFcipa0UQ==,type:str]
    version: 3.13.3
