apiVersion: v1
kind: Secret
metadata:
    name: minio-s3-creds
    namespace: observability
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:daEK4bpqQxhc4lLI,iv:zGIH1Uf4cUTULkWCzZPeb6Vq9oFXJpgLomDpv2kaCGY=,tag:Lq3lX2qDVfQANDCJs7HiJw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Rdxv3IFo5MrcIYutLst2jySiPA+jMY4An0iqK5g41lM=,iv:bk4+F36SCFmpOeXsmCY8Pu4Ygf0x3Lw906vFUVEUQAY=,tag:VN+wB+z0GZQKKlcxCE5f+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUnFBUlBXR3dqbVVYWmto
            bTY1MlNLaXZuVGpCSmFmN25GKzIzOTJwdVd3CjBubTcxNjVMQ2NlOUVNTGtmOG1z
            Tm1OS3lseXB5aVRtYVhRRWJ6SmlIWGcKLS0tIHFkZkdhREdDQ1liTTFYTmU4MnJ3
            L0ZzQ2U5VWVpSjJxUk1zOGovMVlzVXMKSlZ+ZNrIsRoZo2ubDh+XHp5buDbbNsah
            klInaoWZG9nvJ/g1zi1pbEre6uNOllJ2RETsTX0RGuZSUN8YXVVBzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1skrf3yyvljnepgfjpz8tf205tygaycxh68h7t2c6amwtaf0qsgjqzd743s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T00:41:52Z"
    mac: ENC[AES256_GCM,data:IIeutCYrmTujq1dl9ud8VpE0HGguhq9y2GulIzusnGU2F8y+SUy2E67Ks3vPeohfNHqAaZNlyhESrgk/PBpXrkaTU/yBNBs+yeI6LXss1ZUE/jRvOw4DndoAbx0T6XGMh5FBGAzlIuM+2Ej72Vdw8vsV26rX6YcaW2GjKBkZMhE=,iv:NFrrNPpCNxSvPAwyIg5DxtSAN6sEIAD8iEl+N1ineR0=,tag:hhNKDbZ/2UAfbmFHicDAPg==,type:str]
    version: 3.13.3
