apiVersion: v1
kind: Secret
metadata:
    name: velero-s3-creds
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:alcPMBMXJ4ISKhafHPvvBCeul2wWqEi5pQVDJzx45EvVx7darFK9Pr2pqtCAaj3h8BYSSMbaVblVORN13XcSmlEkhIWenYVIBCW4MOkVjsSqPygr/ne90W6BgTdTC69Y,iv:Z6aoAKMncj8w3lt5c1/qo+4ymsejaPKv4zWaJhGLda0=,tag:KD93mq+oN9tywwJgKJ20sg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM0hyNEdUbHNyQWpXWUJQ
            NVZJa205TUtLV0NxQTVMa2Zad2JZSGlTS0JFClM5d2QwN0NFRkxEbENmRGFSdHFY
            bUl4cm5hbmFwZXZrWHpLS2hiVi9pbHcKLS0tIGxEZHJNT0FDVlo2N3R4Qm5OODFs
            eTluV2xrREZsYnRWSzlLaHVobmoyeFkKXr/bMlZGuuhNhmlaNVmrocmY3ZO5LLfS
            0mgghpjbYzCpq1hmcLS42b2Keeng2YD1+ogEUaUezz1JJmCBrb/IbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1skrf3yyvljnepgfjpz8tf205tygaycxh68h7t2c6amwtaf0qsgjqzd743s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T00:58:38Z"
    mac: ENC[AES256_GCM,data:XYZPafDatqjFnd8f8pEe/g1EL7tX/oMr2hEoYX/aIo4pjNIH9f5wPbWCCzBOprz/uBmJtYQ9aDdOKgwrLFicoPt5/zZ6Ak2wNL7FAunDGiQftDypNtmDnAKuSWH6x4ENp6hEYja0S/SnE3A7UBK07y5Kd5rAgQIjBatm7MimMHA=,iv:B5hD0bgggQxaDLIW5BRkt8jf94t956tqFbCWpUYd/Hc=,tag:IC6+R6YzWTX2YV85vtso2w==,type:str]
    version: 3.13.3
