apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/CoreyC315/homelab-devops.git"
    path: kubernetes/apps/kyverno-policies
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true # first sync races the Kyverno CRDs
