apiVersion: apps/v1
kind: Deployment
metadata:
  name: komga
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komga
  template:
    metadata:
      labels:
        app: komga
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: komga
          image: gotson/komga:1.24.4
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: TZ
              value: America/Detroit
          ports:
            - containerPort: 25600
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: komga-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: irminsul-records-celestia-pvc
