apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: celestia-nfs
provisioner: nfs.csi.k8s.io # Must match the driver name
parameters:
  server: 192.168.1.210
  share: /volume1/Media
reclaimPolicy: Retain # IMPORTANT: Keeps your movies if you delete the PVC
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
