apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      # --- REQUIRED FOR WIRE GUARD ROUTING ---
      securityContext:
        sysctls:
          - name: net.ipv4.conf.all.src_valid_mark
            value: "1"
      containers:
        # --- GLUETUN ---
        - name: gluetun
          image: qmcgaw/gluetun:latest
          securityContext:
            privileged: true # Allows Gluetun to rewrite the pod routing table
            capabilities:
              add: ["NET_ADMIN"]
          envFrom:
            - secretRef:
                name: protonvpn-secret
          env:
            - name: WIREGUARD_IMPLEMENTATION
              value: "userspace"
            - name: WIREGUARD_MTU
              value: "1280"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: VPN_PORT_FORWARDING_PROVIDER
              value: "protonvpn"
            - name: VPN_PORT_FORWARDING_UP_COMMAND
              value: "/bin/sh -c 'wget -qO- --post-data \"json={\\\"listen_port\\\":{{PORT}}}\" http://localhost:8080/api/v2/app/setPreferences'"
            - name: HTTP_CONTROL_SERVER_ADDRESS
              value: ":8000"
            # Updated 2026 DNS variables
            - name: DNS_UPSTREAM_RESOLVER_TYPE
              value: "plain"
            - name: DNS_UPSTREAM_PLAIN_ADDRESSES
              value: "1.1.1.1"

        # --- QBITTORRENT ---
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: WEBUI_PORT
              value: "8080"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: qbittorrent-data-pvc
