apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance
  namespace: glance
  annotations:
    cert-manager.io/cluster-issuer: homelab-local-ca
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - glance.local
      secretName: glance-local-tls
  rules:
    - host: glance.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glance
                port:
                  number: 80
